dist: trusty

language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "pypy"

addons:
  apt:
    packages:
      - graphicsmagick
      - zlib1g-dev
      - libopenjpeg2
      - libopenjpeg-dev
      # With Xenial this will be:
      # - libopenjp2-7
      # - libopenjp2-7-dbg

install:
  - pip install Pillow nose
  - python setup.py install

script:
- nosetests
