language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "pypy"
addons:
  apt:
    packages:
      - graphicsmagick
      - zlib1g-dev
      - libopenjp2-7-dev
install:
  - pip install Pillow nose
  - python setup.py install
script:
- nosetests
